const history_questions = [
  {
    id: 1,
    question: "En que año se descubrio América?",
    alt_one: "1412",
    alt_two: "1539",
    alt_three: "1489",
    alt_four: "1512",
    alt_five: "1492",
  },
  {
    id: 2,
    question: "De que color era el caballo blanco de napoleon?",
    alt_one: "Negro",
    alt_two: "Verde",
    alt_three: "Cafe",
    alt_four: "Gris",
    alt_five: "Blanco",
  },
  {
    id: 3,
    question:
      "Cuales fueron las ciudades de Japon donde cayeron bombas atomicas?",
    alt_one: "Tokyo y nagasaki",
    alt_two: "Hiroshima y Kyoto",
    alt_three: "Hiroshima y Osaka",
    alt_four: "Osaka y Nagoya",
    alt_five: "Hiroshima y Nagasaki",
  },
  {
    id: 4,
    question: "Como se llama el primer hombre que piso la Luna?",
    alt_one: "Michael Collins",
    alt_two: "Rick Armstrong",
    alt_three: "Mark Armstrong",
    alt_four: "Richard Nixon",
    alt_five: "Neil Armstrong",
  },
  {
    id: 5,
    question: "Donde sucedio el terremoto mas grande de la historia?",
    alt_one: "Tokyo, Japon 2011",
    alt_two: "océano Índico 2004",
    alt_three: "Constitucion Chile 2010",
    alt_four: "Alaska 1964",
    alt_five: "Valdivia, Chile 1960",
  },
  {
    id: 6,
    question: "En que fecha se anuncio el primer Iphone?",
    alt_one: "13 de diciembre de 2006",
    alt_two: "15 de mayo de 2008",
    alt_three: "24 de noviembre de 2007",
    alt_four: "27 de marzo de 2008",
    alt_five: "9 de enero de 2007",
  },
  {
    id: 7,
    question: "En que fecha se cayo el muro de Berlin?",
    alt_one: "14 de octubre de 1990",
    alt_two: "5 de mayo de 1988",
    alt_three: "15 de septiembre de 1989",
    alt_four: "22 de agosto de 1987",
    alt_five: "9 de noviembre de 1989",
  },
  {
    id: 8,
    question: "Quien fue el inventor de la television?",
    alt_one: "Henry M. Leland en 1932",
    alt_two: "Schuyler Skaats Wheeler en 1925",
    alt_three: "Alexander Bain en 1918",
    alt_four: "William Dubilier en 1920",
    alt_five: "John Logie Baird en 1923",
  },
];

export default history_questions