const math_questions = [
  {
    id: 1,
    question:
      "2, 3, 5, 8, 13, 21, 34, 55... Siguiendo la secuencia, Cual es el siguiente numero?",
    alt_one: "74",
    alt_two: "78",
    alt_three: "89",
    alt_four: "92",
    alt_five: "101",
    answer: "89",
  },
  {
    id: 2,
    question:
      "Cual es el tipo de triangulo en el cual todos los angulos internos son iguales?",
    alt_one: "Isoceles",
    alt_two: "Escaleno",
    alt_three: "Rectangulo",
    alt_four: "Obtangulo",
    alt_five: "Equilatero",
    answer: "Equilatero",
  },
  {
    id: 3,
    question: "SACO es a ASCO lo que 7683 es a...?",
    alt_one: "6873",
    alt_two: "7863",
    alt_three: "6783",
    alt_four: "3786",
    alt_five: "3867",
    answer: "6783",
  },
  {
    id: 4,
    question: "Qué grupo continúa la siguiente serie: 2Z3, 4Y5, 6X7...?",
    alt_one: "9X8",
    alt_two: "8W9",
    alt_three: "8V9",
    alt_four: "9V9",
    alt_five: "8Y9",
    answer: "8W9",
  },
  {
    id: 5,
    question:
      "Una madre tiene 40 años y su hijo tiene 10. ¿Cuántos años deben pasar para que la edad de la madre sea el triple que la edad de su hijo?",
    alt_two: "2 años",
    alt_three: "10 años",
    alt_four: "7 años",
    alt_one: "5 años",
    alt_five: "12 años",
    answer: "5 años",
  },
  {
    id: 6,
    question: "Cuántos cuartos son seis mitades?",
    alt_one: "5/4",
    alt_two: "8/4",
    alt_three: "6/4",
    alt_four: "10/4",
    alt_five: "12/4",
    answer: "12/4",
  },
  {
    id: 7,
    question:
      "Fíjate en la siguiente operación: 10 () 3 () 9 = 39. ¿Cuáles son los operadores correctos para lograr el resultado de dicha operación?",
    alt_one: "( * ) ( + )",
    alt_two: "( + ) ( * )",
    alt_three: "( * ) ( - )",
    alt_four: "( + ) ( + )",
    alt_five: "( - ) ( + )",
    answer: "( * ) ( + )",
  },
  {
    id: 8,
    question:
      "Conduces un autobús en el que se montan 18 personas. En la siguiente parada se bajan 5 pero suben otras 13. Al llegar a la siguiente estación, se bajan 21 y suben 4. ¿Cuántas personas quedan en el autobús?",
    alt_one: "7",
    alt_two: "5",
    alt_three: "8",
    alt_four: "10",
    alt_five: "9",
    answer: "9",
  },
  {
    id: 9,
    question: "¿Cuántas veces se puede restar 1 a la cifra 1111??",
    alt_one: "1",
    alt_two: "1010",
    alt_three: "1000",
    alt_four: "1110",
    alt_five: "1111",
    answer: "1",
  },
  {
    id: 10,
    question:
      "Cinco máquinas son capaces de redactar 5 artículos en cinco minutos. Con este ritmo de producción, ¿Cuánto tiempo necesitan 100 máquinas para elaborar 100 artículos?",
    alt_one: "100 minutos",
    alt_two: "20 minutos",
    alt_three: "5 minutos",
    alt_four: "2 minutos",
    alt_five: "1 minuto",
    answer: "5 minutos",
  },
  {
    id: 11,
    question: "",
    alt_one: "",
    alt_two: "",
    alt_three: "",
    alt_four: "",
    alt_five: "",
    answer: "",
  },
  {
    id: 12,
    question: "",
    alt_one: "",
    alt_two: "",
    alt_three: "",
    alt_four: "",
    alt_five: "",
    answer: "",
  },
  {
    id: 13,
    question: "",
    alt_one: "",
    alt_two: "",
    alt_three: "",
    alt_four: "",
    alt_five: "",
    answer: "",
  },
  {
    id: 14,
    question: "",
    alt_one: "",
    alt_two: "",
    alt_three: "",
    alt_four: "",
    alt_five: "",
    answer: "",
  },
  {
    id: 15,
    question: "",
    alt_one: "",
    alt_two: "",
    alt_three: "",
    alt_four: "",
    alt_five: "",
    answer: "",
  },
];

export default math_questions;
