const music_questions = [
  {
    id: 1,
    question: "Cual es el nombre del protagonista de one piece?",
    alt_one: "Roronoa Zoro",
    alt_two: "Monkey D Garp",
    alt_three: "Portgas D ace",
    alt_four: "Monkey D Luffy",
    alt_five: "Naruto",
    answer: "Monkey D Luffy",
  },
  {
    id: 2,
    question:
      "Cual es el numero que lleva Hizoka durante el examen del cazador?",
    alt_one: "El numero 4",
    alt_two: "El numero 12",
    alt_three: "El numero 69",
    alt_four: "El numero 7",
    alt_five: "El numero 44",
    answer: "El numero 44",
  },
  {
    id: 3,
    question:
      "Cual es la esfera del dragon que Goku guardaba en su casa en Dragon Ball?",
    alt_one: "La esfera de 6 estrellas",
    alt_two: "La esfera de 4 estrellas",
    alt_three: "La esfera de 2 estrellas",
    alt_four: "La esfera de 7 estrellas",
    alt_five: "La esfera de 3 estrellas",
    answer: "La esfera de 4 estrellas",
  },
  {
    id: 4,
    question: "Cual es el nombre del primer pokemon de ASH Ketchup?",
    alt_one: "Charmander",
    alt_two: "Pidgey",
    alt_three: "Pikachu",
    alt_four: "Squirtle",
    alt_five: "Metapod",
    answer: "Pikachu",
  },
  {
    id: 5,
    question:
      "En el anime de HXH 2011, a que categoria de Hatsu pertenecia Gon?",
    alt_one: "Especialista",
    alt_two: "Manipulador",
    alt_three: "Intensificador",
    alt_four: "Transformador",
    alt_five: "Emisor",
    answer: "Intensificador",
  },
  {
    id: 6,
    question:
      "En el anime de Hajime no Ippo, cual es el nombre del maximo rival de Makunouchi Ippo?",
    alt_one: "Takeshi Sendou",
    alt_two: "Volg Zangief",
    alt_three: "Ichiro Miyata",
    alt_four: "Date Eiji",
    alt_five: "Wally",
    answer: "Takeshi Sendou",
  },
  {
    id: 7,
    question:
      "En el anime de Dragon Ball Z, Cual es el nombre del hijo de Vegeta?",
    alt_one: "Gohan",
    alt_two: "Bills",
    alt_three: "Turles",
    alt_four: "Goten",
    alt_five: "Trunks",
    answer: "Trunks",
  },
  {
    id: 8,
    question: "En el anime de Naruto, cual es el apodo de Kakashi Hatake?",
    alt_one: "El ninja que copia",
    alt_two: "El heredero del sharingan",
    alt_three: "Kakashi el del sharingan",
    alt_four: "Lobo blanco de Konoha",
    alt_five: "El cuarto Sanin",
    answer: "El ninja que copia",
  },
  {
    id: 9,
    question: "Cual es el sobrenombre de Sakata Gintoki del anime Gintama?",
    alt_one: "Yakusa",
    alt_two: "Colmillo blanco",
    alt_three: "Shiroyasha",
    alt_four: "El demonio de Edo",
    alt_five: "El superviviente de Hathsin",
    answer: "Shiroyasha",
  },
  {
    id: 10,
    question:
      "De los siguientes animes, Cual es el unico que no es considerado Shonen?",
    alt_one: "One Piece",
    alt_two: "Naruto",
    alt_three: "One punch Man",
    alt_four: "Bleach",
    alt_five: "Chainsaw Man",
    answer: "One punch Man",
  },
];

export default music_questions;
